dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "file://../loki"
  version: "^2.12.2"
- name: "promtail"
  condition: promtail.enabled
  repository: "file://../promtail"
  version: "^3.11.0"
- name: "fluent-bit"
  condition: fluent-bit.enabled
  repository: "file://../fluent-bit"
  version: "^2.3.0"